Repository jatinkumar027/Nourishing-Skills, pull requests merged in 2022-10, with the labels that each got.

#11 Create Armstrong_Number.py
  Python/Data Structure and Algorithms/Armstrong_Number.py
Labels: needs improvement, pending for requester

#14 Create Remove_duplicates.py
  Python/Data Structure and Algorithms/Remove_duplicates.py
Labels: pending for requester

#21 uncommon words in two string
  Python/Data Structure and Algorithms/replace_occurence_of_string.py
  Python/Data Structure and Algorithms/uncommon_words_from_two_string.py
Labels: pending for requester

#20 Added checkStringForAllVowels code
  Python/Data Structure and Algorithms/checkStringForAllVowels.py
Labels: pending for requester

#30 merge sort
  Python/Data Structure and Algorithms/mergesort.py
Labels: hacktoberfest, hacktoberfest-accepted, algorithms

#17 The code for Bubble Sort algorithm was added
  Python/Data Structure and Algorithms/BubbleSort.py
Labels: pending for requester

#43 Create tower_of_hanoi.py
  Python/Data Structure and Algorithms/tower_of_hanoi.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#46 Sum even factors
  Python/Data Structure and Algorithms/SumEvenFactors.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#48 Create Matching_Characters.py
  Matching_Characters.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#51 Create Sum_Of_Odd_Factors.py
  Python/Data Structure and Algorithms/Sum_Of_Odd_Factors.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#65 checking if the digits of the number divides the number
  Python/Data Structure and Algorithms/date.py
  digits.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#63 code for yesterday's , today's and tomorrow's date
  Python/Data Structure and Algorithms/date.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#67 Python Remove Empty Tuple List
  Python/Data Structure and Algorithms/Break_list_into_n.py
  Python/Data Structure and Algorithms/Remove_Empty_Tuples_List.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#68 Create Program_to_find_cumulative_sum.py
  Python/Data Structure and Algorithms/Program_to_find_cumulative_sum.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#69 Create Add_two_metrices.py
  Python/Data Structure and Algorithms/Add_two_metrices.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#70 Create Extract_digits_from_tuple_list.py
  Python/Data Structure and Algorithms/Extract_digits_from_tuple_list.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#66 Create Show_Date.py
  Python/Data Structure and Algorithms/Show_Date.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#72 cycle detection in undirected graph
  Python/Data Structure and Algorithms/cycle_detection_graph.py
Labels: hacktoberfest, hacktoberfest-accepted, problems

#71 sum of odd and even number code in python
  Python/Data Structure and Algorithms/sum of odd_even_no.py
Labels: hacktoberfest, hacktoberfest-accepted, problems
